/* =====================================================================
   R6 Operator Randomiser - Firebot Custom Widget : onShow JS
   Generated by tools/build-firebot.js (hosted mode).

   Runs when the widget is shown: defines the roller, then rolls once.
   Re-roll later with the "Send Message to Custom Widget" effect.
   ===================================================================== */

var CONFIG = {
  scale:     1,      // overall size multiplier
  spin:      4200,   // defender reel duration, ms
  stagger:   900,    // attacker lands this much later, ms
  confetti:  true,
  assetBase: "http://localhost:7472/overlay-resources/r6/"
};

var ATTACKERS = [
  ["Sledge","sledge.svg"],
  ["Thatcher","thatcher.svg"],
  ["Ash","ash.svg"],
  ["Thermite","thermite.svg"],
  ["Twitch","twitch.svg"],
  ["Montagne","montagne.svg"],
  ["Glaz","glaz.svg"],
  ["Fuze","fuze.svg"],
  ["Blitz","blitz.svg"],
  ["IQ","iq.svg"],
  ["Buck","buck.svg"],
  ["Blackbeard","blackbeard.svg"],
  ["Capitão","capitao.svg"],
  ["Hibana","hibana.svg"],
  ["Jackal","jackal.svg"],
  ["Ying","ying.svg"],
  ["Zofia","zofia.svg"],
  ["Dokkaebi","dokkaebi.svg"],
  ["Lion","lion.svg"],
  ["Finka","finka.svg"],
  ["Maverick","maverick.svg"],
  ["Nomad","nomad.svg"],
  ["Gridlock","gridlock.svg"],
  ["Nøkk","nokk.svg"],
  ["Amaru","amaru.svg"],
  ["Kali","kali.svg"],
  ["Iana","iana.svg"],
  ["Ace","ace.svg"],
  ["Zero","zero.svg"],
  ["Flores","flores.svg"],
  ["Osa","osa.svg"],
  ["Sens","sens.svg"],
  ["Grim","grim.svg"],
  ["Brava","brava.svg"],
  ["Ram","ram.svg"],
  ["Deimos","deimos.svg"],
  ["Striker","striker.svg"],
  ["Rauora","rauora.svg"]
];

var DEFENDERS = [
  ["Smoke","smoke.svg"],
  ["Mute","mute.svg"],
  ["Castle","castle.svg"],
  ["Pulse","pulse.svg"],
  ["Doc","doc.svg"],
  ["Rook","rook.svg"],
  ["Jäger","jager.svg"],
  ["Bandit","bandit.svg"],
  ["Tachanka","tachanka.svg"],
  ["Kapkan","kapkan.svg"],
  ["Frost","frost.svg"],
  ["Valkyrie","valkyrie.svg"],
  ["Caveira","caveira.svg"],
  ["Echo","echo.svg"],
  ["Mira","mira.svg"],
  ["Lesion","lesion.svg"],
  ["Ela","ela.svg"],
  ["Vigil","vigil.svg"],
  ["Alibi","alibi.svg"],
  ["Maestro","maestro.svg"],
  ["Clash","clash.svg"],
  ["Kaid","kaid.svg"],
  ["Mozzie","mozzie.svg"],
  ["Warden","warden.svg"],
  ["Goyo","goyo.svg"],
  ["Wamai","wamai.svg"],
  ["Oryx","oryx.svg"],
  ["Melusi","melusi.svg"],
  ["Aruni","aruni.svg"],
  ["Thunderbird","thunderbird.svg"],
  ["Thorn","thorn.svg"],
  ["Azami","azami.svg"],
  ["Solis","solis.svg"],
  ["Fenrir","fenrir.svg"],
  ["Tubarão","tubarao.svg"],
  ["Sentry","sentry.svg"],
  ["Skopós","skopos.svg"],
  ["Denari","denari.svg"]
];

(function () {
  var root = containerElement.querySelector(".r6");
  if (!root) { return; }
  root.style.setProperty("--scale", CONFIG.scale);

  function srcFor(op) { return CONFIG.assetBase + op[1]; }

  /* ---- randomness: CSPRNG + rejection sampling, no seed, no state ---- */
  function randomInt(max) {
    if (max <= 1) return 0;
    if (window.crypto && window.crypto.getRandomValues) {
      var limit = Math.floor(4294967296 / max) * max;
      var buf = new Uint32Array(1), v;
      do { window.crypto.getRandomValues(buf); v = buf[0]; } while (v >= limit);
      return v % max;
    }
    return Math.floor(Math.random() * max);
  }
  function pick(a) { return a[randomInt(a.length)]; }
  function shuffled(a) {
    var out = a.slice();
    for (var i = out.length - 1; i > 0; i--) {
      var j = randomInt(i + 1), t = out[i]; out[i] = out[j]; out[j] = t;
    }
    return out;
  }

  /* ---- confetti ---- */
  var canvas = root.querySelector("canvas.r6-confetti");
  var ctx = canvas.getContext("2d");
  var parts = [], raf = null;

  function sizeCanvas() {
    var dpr = window.devicePixelRatio || 1;
    var r = root.getBoundingClientRect();
    canvas.width = Math.max(1, Math.floor(r.width * dpr));
    canvas.height = Math.max(1, Math.floor(r.height * dpr));
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  }
  function tick() {
    var r = root.getBoundingClientRect();
    ctx.clearRect(0, 0, r.width, r.height);
    for (var i = parts.length - 1; i >= 0; i--) {
      var p = parts[i];
      p.vy += 0.34; p.vx *= 0.992;
      p.x += p.vx; p.y += p.vy; p.rot += p.vr; p.life -= 0.0075;
      if (p.life <= 0 || p.y - 40 > r.height) { parts.splice(i, 1); continue; }
      ctx.save();
      ctx.translate(p.x, p.y); ctx.rotate(p.rot);
      ctx.globalAlpha = Math.max(0, Math.min(1, p.life));
      ctx.fillStyle = p.color;
      ctx.fillRect(-p.w / 2, -p.h / 2, p.w, p.h);
      ctx.restore();
    }
    raf = parts.length ? requestAnimationFrame(tick) : null;
    if (!raf) ctx.clearRect(0, 0, r.width, r.height);
  }
  function burst(x, y, colors) {
    for (var i = 0; i < 70; i++) {
      var ang = (-Math.PI / 2) + (Math.random() - 0.5) * 1.9;
      var spd = 7 + Math.random() * 11;
      parts.push({
        x: x, y: y, vx: Math.cos(ang) * spd, vy: Math.sin(ang) * spd,
        w: 5 + Math.random() * 6, h: 8 + Math.random() * 8,
        rot: Math.random() * Math.PI * 2, vr: (Math.random() - 0.5) * 0.32,
        color: colors[Math.floor(Math.random() * colors.length)], life: 1
      });
    }
    if (!raf) raf = requestAnimationFrame(tick);
  }
  function celebrate() {
    if (!CONFIG.confetti) return;
    sizeCanvas();
    var base = root.getBoundingClientRect();
    var panels = root.querySelectorAll(".r6-panel");
    for (var i = 0; i < panels.length; i++) {
      var w = panels[i].querySelector(".r6-window").getBoundingClientRect();
      var colors = panels[i].getAttribute("data-side") === "attack"
        ? ["#0dd1cb", "#7fe8e5", "#ffffff", "#089b96"]
        : ["#ff9124", "#ffc97a", "#ffffff", "#e0620a"];
      // The canvas lives inside the widget, so use container-relative coords.
      burst(w.left - base.left + w.width / 2,
            w.top - base.top + w.height * 0.62, colors);
    }
  }

  /* ---- reel ---- */
  var LOOPS = 5;
  function tileHtml(op) {
    return '<div class="r6-tile"><div class="r6-emblem"><img src="' + srcFor(op) +
           '" alt="" draggable="false"></div><div class="r6-name">' + op[0] + '</div></div>';
  }
  function makeReel(side, pool) {
    var strip = root.querySelector('[data-reel="' + side + '"]');
    var win = strip.parentElement;
    var panel = win.closest(".r6-panel");
    return function (duration, done) {
      var winner = pick(pool);
      var tiles = [];
      for (var i = 0; i < LOOPS; i++) tiles = tiles.concat(shuffled(pool));
      var idx = tiles.length;
      tiles.push(winner);
      tiles = tiles.concat(shuffled(pool).slice(0, 4));

      panel.classList.remove("locked");
      strip.classList.remove("unblur");
      strip.style.transition = "none";
      strip.style.transform = "translate3d(0,0,0)";
      strip.innerHTML = tiles.map(tileHtml).join("");

      var tileH = win.getBoundingClientRect().height;
      void strip.offsetHeight;

      strip.classList.add("blurred");
      strip.style.transition = "transform " + duration + "ms cubic-bezier(.16,.86,.2,1)";
      strip.style.transform = "translate3d(0," + (-idx * tileH) + "px,0)";

      setTimeout(function () {
        strip.classList.remove("blurred");
        strip.classList.add("unblur");
      }, Math.max(0, duration - 1100));

      var settled = false;
      function settle(e) {
        if (e && e.propertyName !== "transform") return;
        if (settled) return;
        settled = true;
        strip.removeEventListener("transitionend", settle);
        var landed = strip.children[idx];
        if (landed) landed.classList.add("is-winner");
        panel.classList.add("locked");
        done();
      }
      strip.addEventListener("transitionend", settle);
      setTimeout(settle, duration + 250);
    };
  }

  var spinDefend = makeReel("defend", DEFENDERS);
  var spinAttack = makeReel("attack", ATTACKERS);
  var spinning = false;

  function roll() {
    if (spinning) return;
    spinning = true;
    parts = [];
    var panels = root.querySelectorAll(".r6-panel");
    for (var i = 0; i < panels.length; i++) panels[i].classList.remove("locked");
    var left = 2;
    function done() { if (--left === 0) { spinning = false; celebrate(); } }
    spinDefend(CONFIG.spin, done);
    spinAttack(CONFIG.spin + CONFIG.stagger, done);
  }

  // Keyed by widget id so onMessage can find it, and so two copies of the
  // widget on one overlay do not fight over the same global.
  window.__r6 = window.__r6 || {};
  window.__r6[widgetId] = { roll: roll };
  window.__r6.last = { roll: roll };

  sizeCanvas();

  // Warm the image cache, then roll. Never block longer than 2s.
  var all = ATTACKERS.concat(DEFENDERS), left = all.length, started = false;
  function go() { if (!started) { started = true; roll(); } }
  all.forEach(function (op) {
    var img = new Image();
    img.onload = img.onerror = function () { if (--left <= 0) go(); };
    img.src = srcFor(op);
  });
  setTimeout(go, 2000);
})();
